name: build-and-test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Behave tests
        run: |
          python -m behave -f behave_html_formatter:HTMLFormatter -o reports/report.html

      - name: Upload artifact (HTML report + screenshots)
        uses: actions/upload-artifact@v4
        with:
          name: behave-reports
          path: |
            reports/report.html
            reports/screenshots/
